
- alias: 'Toilet lights on in evening (early sunset)'
  trigger:
    platform: sun
    event: sunset
    offset: "-0:10:00"
  condition:
    condition: time
    before: '20:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.toilet
        brightness_pct: 100

- alias: 'Dim toilet lights at kids bedtime'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:10:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.toilet
        brightness_pct: 1

- alias: 'Toilet lights on in evening (late sunset)'
  trigger:
    platform: sun
    event: sunset
    offset: "-0:10:00"
  condition:
    condition: time
    after: '20:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.toilet
        brightness_pct: 1

- alias: 'Toilet lights off in morning'
  trigger:
    platform: sun
    event: sunrise
    offset: "0:10:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.toilet

- alias: 'Night light on at bedtime'
  trigger:
    platform: time
    at: '19:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.night_light_2
        rgb_color: [255, 0, 190]
        brightness_pct: 80

- alias: 'Night red at 5am'
  trigger:
    platform: time
    at: '05:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.night_light_2
        rgb_color: [255, 0, 0]
        brightness_pct: 80

- alias: 'Night light green in morning (workdays)'
  trigger: 
    platform: time
    at: '07:15:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'on'
      - condition: state
        entity_id: 'input_boolean.on_holiday'
        state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.night_light_2
        rgb_color: [0, 255, 0]
        brightness_pct: 80
    - delay:
        minutes: 15
    - service: light.turn_off
      entity_id: light.night_light_2

- alias: 'Night light green in morning (non-workdays)'
  trigger: 
    platform: time
    at: '08:15:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: 'binary_sensor.workday_sensor'
        state: 'off'
      - condition: state
        entity_id: 'input_boolean.on_holiday'
        state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.night_light_2
        rgb_color: [0, 255, 0]
        brightness_pct: 80
    - delay:
        minutes: 15
    - service: light.turn_off
      entity_id: light.night_light_2

