
timer:
  toilet_light_timeout:
    duration: "00:02:00"

input_select:
  last_door:
    name: "Last Opened Door"
    options:
      - "Kitchen"
      - "Bedroom"
      - "Manual Override"

automation:
  - alias: Toilet Motion Light
    trigger:
      platform: state
      entity_id: binary_sensor.toilet_motion
      from: "off"
      to: "on"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states.input_select.last_door.state != 'Manual Override' }}"
        - condition: or
          conditions:
            - condition: sun
              after: sunset
              after_offset: "-00:20:00"
            - condition: sun
              before: sunrise
              before_offset: "00:20:00"
    action:
      - service: timer.start
        entity_id: timer.toilet_light_timeout
      - service: light.turn_on
        entity_id: light.toilet
        data_template:
          brightness_pct: "{% if states.input_select.last_door.state == 'Bedroom' %}1{% else %}100{% endif %}"

  - alias: Toilet Light Timeout
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.toilet_light_timeout
    condition:
      condition: template
      value_template: "{{ states.input_select.last_door.state != 'Manual Override' }}"
    action:
      - service: light.turn_off
        entity_id: light.toilet

  - alias: Set Last Opened Door
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_hall_door
        from: "off"
        to: "on"
      - platform: state
        entity_id: !secret bed1_door_entity
        from: "off"
        to: "on"
    action:
      service: input_select.select_option
      entity_id: input_select.last_door
      data_template:
          option: "{% if trigger.entity_id == 'binary_sensor.kitchen_hall_door' %}Kitchen{% else %}Bedroom{% endif %}"

